### PR TITLE
Respond to both GET and POST

### PR DESCRIPTION
**Pull request by adammck**
According to [the docs](http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/MakingRequests_MakingQueryRequestsArticle.html), SQS accepts both GET and POST requests. This small PR expands the existing POST handlers to do that. I also added a `/ping` handler to test whether the service is up, since `GET /` is no longer a valid request (because the Action parameter is required).

### CODE REVIEW

**Comment by pfhayes** [comment]
+1 to this PR - this is required to work with some of the AWS libraries which make requests via GET (notably, Python's boto)

**Comment by chrisleck** [comment]
Any word on this PR?

**Comment by slobo** [comment]
+1 - Perl Amazon::SQS::Simple also uses GET for all requests < 4k by default

**Comment by tiwilliam** [comment]
Thanks @adammck! This was resolved and merged on command line, closing.

**Pull request closed without merging**
